//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace signalAcquirer.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class sample
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public sample()
        {
            this.sample_data = new HashSet<sample_data>();
        }
    
        public int Id { get; set; }
        public int id_person { get; set; }
        public int signal_type { get; set; }
        public System.DateTime acquisition_date { get; set; }
        public int frequency { get; set; }
        public string unit { get; set; }
    
        public virtual people people { get; set; }
        public virtual signal_type signal_type1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sample_data> sample_data { get; set; }
    }
}
