//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace signalAcquirer.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class sample_data
    {
        public int Id { get; set; }
        public int id_sample { get; set; }
        public int order { get; set; }
        public Nullable<decimal> A0 { get; set; }
        public Nullable<int> olimex_count { get; set; }
    
        public virtual sample sample { get; set; }
    }
}
